#!/usr/bin/env bash
# provision-device.sh - Set up a new Coco device for deployment
# Usage: sudo ./scripts/provision-device.sh

set -euo pipefail

COCO_DIR="${COCO_DIR:-/home/pi/coco-device}"
ENV_FILE="${COCO_DIR}/.env"
VERSION_FILE="/etc/coco-agent-version"
LOGROTATE_SRC="${COCO_DIR}/config/logrotate-coco"
LOGROTATE_DEST="/etc/logrotate.d/coco"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# Check if running as root
if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root (use sudo)"
    exit 1
fi

echo "============================================"
echo "  Coco Device Provisioning"
echo "============================================"
echo ""

# Check for existing .env
if [[ -f "$ENV_FILE" ]]; then
    log_warn ".env already exists at $ENV_FILE"
    read -p "Overwrite existing configuration? [y/N] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log_info "Keeping existing configuration"
        exit 0
    fi
fi

# Prompt for required values
echo ""
log_info "Enter configuration values (press Enter for defaults where shown)"
echo ""

# Participant ID (required)
while true; do
    read -p "Participant ID (e.g., participant-001): " PARTICIPANT_ID
    if [[ -n "$PARTICIPANT_ID" ]]; then
        break
    fi
    log_error "Participant ID is required"
done

# Device ID (auto-generate or custom)
DEFAULT_DEVICE_ID="coco-$(hostname)-$(date +%s | tail -c 5)"
read -p "Device ID [${DEFAULT_DEVICE_ID}]: " DEVICE_ID
DEVICE_ID="${DEVICE_ID:-$DEFAULT_DEVICE_ID}"

# Backend URL
read -p "Backend URL [https://coco-backend.fly.dev]: " BACKEND_URL
BACKEND_URL="${BACKEND_URL:-https://coco-backend.fly.dev}"

# Ingest token
read -p "Ingest Service Token: " INGEST_TOKEN
if [[ -z "$INGEST_TOKEN" ]]; then
    log_warn "No ingest token provided - session data won't be sent to backend"
fi

# OpenAI API Key
read -p "OpenAI API Key: " OPENAI_KEY
if [[ -z "$OPENAI_KEY" ]]; then
    log_error "OpenAI API Key is required for TTS/STT/LLM"
    exit 1
fi

# Audio device configuration
echo ""
log_info "Audio device configuration (run 'aplay -l' to list devices)"
read -p "Audio Output Device [pulse]: " AUDIO_OUT
AUDIO_OUT="${AUDIO_OUT:-pulse}"
read -p "Audio Input Device [pulse]: " AUDIO_IN
AUDIO_IN="${AUDIO_IN:-pulse}"

# Write .env file
log_info "Writing configuration to $ENV_FILE"
cat > "$ENV_FILE" << EOF
# Coco Device Configuration
# Generated by provision-device.sh on $(date -Iseconds)

# ============================================
# Identity & Backend
# ============================================
COCO_DEVICE_ID=${DEVICE_ID}
COCO_USER_EXTERNAL_ID=${PARTICIPANT_ID}
COCO_PARTICIPANT_ID=${PARTICIPANT_ID}
COCO_BACKEND_URL=${BACKEND_URL}
INGEST_SERVICE_TOKEN=${INGEST_TOKEN}

# ============================================
# OpenAI
# ============================================
OPENAI_API_KEY=${OPENAI_KEY}

# ============================================
# Audio Hardware (ALSA)
# ============================================
COCO_AUDIO_OUTPUT_DEVICE=${AUDIO_OUT}
COCO_AUDIO_INPUT_DEVICE=${AUDIO_IN}
COCO_AUDIO_DISABLE=0

# ============================================
# Logging
# ============================================
COCO_LOG_LEVEL=info
EOF

# Set proper ownership
chown pi:pi "$ENV_FILE"
chmod 600 "$ENV_FILE"
log_info ".env file created with secure permissions"

# Write version file
AGENT_VERSION=$(cd "$COCO_DIR" && git describe --tags --always 2>/dev/null || echo "unknown")
echo "$AGENT_VERSION" > "$VERSION_FILE"
log_info "Version file written: $AGENT_VERSION"

# Install logrotate config
if [[ -f "$LOGROTATE_SRC" ]]; then
    cp "$LOGROTATE_SRC" "$LOGROTATE_DEST"
    log_info "Logrotate configuration installed"
else
    log_warn "Logrotate config not found at $LOGROTATE_SRC"
fi

# Create log directory
mkdir -p /var/log/coco
chown pi:pi /var/log/coco
log_info "Log directory created"

# Reload systemd and restart services
log_info "Reloading systemd daemon..."
systemctl daemon-reload

log_info "Enabling and restarting services..."
for svc in coco-agent-scheduler coco-heartbeat coco-command-poller coco-update; do
    if systemctl list-unit-files "${svc}.timer" &>/dev/null; then
        systemctl enable "${svc}.timer" 2>/dev/null || true
        systemctl restart "${svc}.timer" 2>/dev/null || true
        log_info "  ${svc}.timer enabled and started"
    fi
done

echo ""
echo "============================================"
echo -e "${GREEN}  Provisioning Complete!${NC}"
echo "============================================"
echo ""
echo "Device ID:      $DEVICE_ID"
echo "Participant ID: $PARTICIPANT_ID"
echo "Version:        $AGENT_VERSION"
echo ""
echo "Next steps:"
echo "  1. Test audio: speaker-test -D $AUDIO_OUT -c 1 -t sine -f 440 -l 1"
echo "  2. Test mic:   arecord -D $AUDIO_IN -d 3 -f S16_LE -r 24000 test.wav && aplay test.wav"
echo "  3. Run test:   npm start"
echo "  4. Check logs: tail -f /var/log/coco/agent.log"
echo ""
